### ISSUE TITLE
Error running scanner. Cannot read property 'family'

### ISSUE THREAD

**Issue by sbehrends** [vincentbernat/nodecastor#3]
Hello, just found out about this package. Im trying to Cast some specific app, like in one of the exmaples, but got issues trying the first example in Readme.md.

```
/cast/node_modules/nodecastor/lib/scanner.js:11
      family = options.family || 0, // UNSPEC, can also use 4 or 6.
                      ^

TypeError: Cannot read property 'family' of undefined
    at new Scanner (/cast/node_modules/nodecastor/lib/scanner.js:11:23)
    at Object.module.exports.scan (/cast/node_modules/nodecastor/index.js:5:12)
    at Object.<anonymous> (/cast/demo.js:3:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by vincentbernat** [comment]
Sorry for that. I just pushed a fix and a new version will be released shortly.

**Comment by sbehrends** [comment]
Working :+1: 
Thanks :)
